#!/usr/bin/env python3
"""Automated leakage audit -> docs/leakage_audit.md (all numbers below are computed by this script).

Checks
 1. Truncation invariance: every feature is recomputed on inputs cut at a random time T (bars with ts <= T,
    funding/metrics rows stamped < T + 1 min). Feature rows with ts <= T must equal the full-sample values.
    Any look-ahead (centred window, backward fill, full-sample normalisation, forward as-of join) breaks this.
 2. Book as-of join: every bar's snapshot is stamped strictly before the bar close.
 3. Funding as-of join: the funding record used at t was settled at or before the decision time.
 4. Open-interest join: the OI row used at t was created at least 5 min before the decision time.
 5. Targets: fwd_ret_h(t) == px[t+h]/px[t] - 1 exactly; label_end = ts + h + 1 min.
 6. No feature is (nearly) a copy of a target: max |corr(feature, fwd_ret_h)| and exact-equality search.
 7. Walk-forward folds: purge/embargo respected for every fold and horizon; no development row reaches the holdout.
 8. Learned preprocessing (imputation/scaling) only inside sklearn Pipelines fitted on each training fold.
"""
from __future__ import annotations

import inspect
import sys
from datetime import timedelta
from pathlib import Path

import numpy as np
import polars as pl

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from ethof import features as F  # noqa: E402
from ethof import models as M  # noqa: E402
from ethof import validation as V  # noqa: E402
from ethof.config import Paths, load_config  # noqa: E402

SYM = "ETHUSDT"
FEATS = sorted(set(sum(F.GROUPS.values(), [])))


def main() -> None:
    cfg = load_config()
    paths = Paths(cfg["data_dir"])
    rs = cfg["research"]
    lines = ["# Leakage Prevention and Data Integrity Audit\n",
             "Generated by `scripts/leakage_audit.py`. Every number below is computed by that script.\n"]
    ok_all = True

    def record(name, ok, detail):
        nonlocal ok_all
        ok_all &= bool(ok)
        lines.append(f"### {'PASS' if ok else 'FAIL'}: {name}\n\n{detail}\n")

    # ---------------------------------------------------------------- 1. truncation invariance
    bars = pl.read_parquet(sorted((paths.processed / "bars_1m").glob(f"{SYM}-bars_1m-2024-0[456].parquet"))).sort("ts")
    funding = pl.read_parquet(paths.processed / "funding" / f"{SYM}-funding.parquet")
    metrics = pl.read_parquet(paths.processed / "metrics" / f"{SYM}-metrics.parquet")
    full = F.build_features(bars, funding, metrics).select(["ts"] + FEATS)
    rng = np.random.default_rng(11)
    n_cut = 12
    cuts = np.sort(rng.integers(3 * 1440, bars.height - 1, size=n_cut))
    worst, n_cmp, bad_feats = 0.0, 0, set()
    for c in cuts:
        T = bars["ts"][int(c)]
        tau = T + timedelta(minutes=1)
        trunc = F.build_features(bars.filter(pl.col("ts") <= T), funding.filter(pl.col("ts") < tau),
                                 metrics.filter(pl.col("ts") < tau)).select(["ts"] + FEATS)
        a = full.filter(pl.col("ts") <= T)
        assert a.height == trunc.height
        for f in FEATS:
            x, y = a[f].to_numpy().astype(float), trunc[f].to_numpy().astype(float)
            same_nan = np.isnan(x) == np.isnan(y)
            m = ~np.isnan(x) & ~np.isnan(y)
            diff = np.abs(x[m] - y[m]) / np.maximum(1.0, np.abs(x[m]))
            d = float(diff.max()) if diff.size else 0.0
            n_cmp += int(m.sum())
            if d > 1e-9 or not same_nan.all():
                bad_feats.add(f)
            worst = max(worst, d)
    record("Truncation invariance of all features",
           not bad_feats,
           f"{len(FEATS)} features, {n_cut} random cut points in 2024-04..2024-06 (3 months of bars), "
           f"{n_cmp:,} feature values compared. Max relative difference: {worst:.3g}. "
           f"Features failing: {sorted(bad_feats) or 'none'}.")

    # ---------------------------------------------------------------- research dataset
    rd = pl.read_parquet(paths.processed / "research" / f"{SYM}-research.parquet")
    allbars = pl.scan_parquet(sorted((paths.processed / "bars_1m").glob(f"{SYM}-bars_1m-*.parquet")))

    # 2. book
    b = allbars.select("ts", "book_ts").filter(pl.col("book_ts").is_not_null()).select(
        n=pl.len(), viol=(pl.col("book_ts") >= pl.col("ts") + pl.duration(minutes=1)).sum(),
        min_age_s=((pl.col("ts") + pl.duration(minutes=1)) - pl.col("book_ts")).dt.total_seconds().min()).collect()
    n, viol, min_age = b.row(0)
    record("Book snapshots joined strictly before bar close", viol == 0,
           f"{n:,} bars with a snapshot; violations (snapshot ts >= bar close): {viol}; minimum snapshot age at "
           f"decision time: {min_age} s. Book features are set to null when the snapshot is stale (> "
           f"{cfg['quality']['book_stale_seconds']} s); stale/missing book data are never interpolated.")

    # 3/4. funding + OI joins (recomputed with join keys kept)
    tau = rd.select("ts").with_columns(tau=pl.col("ts") + pl.duration(minutes=1)).sort("tau")
    fj = tau.join_asof(funding.select(fts="ts").sort("fts"), left_on="tau", right_on="fts", strategy="backward")
    fviol = int((fj["fts"] > fj["tau"]).sum())
    record("Funding rate known at decision time", fviol == 0,
           f"{fj['fts'].is_not_null().sum():,} rows matched to a settled funding record; records settled after "
           f"the decision time: {fviol}. Only realised (settled) rates are used, never the next predicted rate.")
    mj = tau.join_asof(metrics.select(mts="ts").with_columns(avail=pl.col("mts") + pl.duration(minutes=5)).sort("avail"),
                       left_on="tau", right_on="avail", strategy="backward")
    lag = (mj["tau"] - mj["mts"]).dt.total_minutes()
    record("Open interest lagged at least 5 minutes", int((lag < 5).sum()) == 0,
           f"Minimum lag between OI create_time and decision time: {lag.min()} min (rule: >= 5 min).")

    # 5. targets
    t_ok, t_detail = True, []
    pxn = rd["px"].to_numpy()
    for h in rs["horizons"]:
        exp = np.full(len(pxn), np.nan)
        exp[:-h] = pxn[h:] / pxn[:-h] - 1
        got = rd[f"fwd_ret_{h}"].to_numpy().astype(float)
        m = ~np.isnan(exp)
        err = float(np.nanmax(np.abs(got[m] - exp[m])))
        le_ok = bool((rd[f"label_end_{h}"] == rd["ts"] + timedelta(minutes=h + 1)).all())
        t_ok &= err < 1e-12 and le_ok and bool(np.isnan(got[-h:]).all())
        t_detail.append(f"h={h}: max |error| {err:.2g}; last {h} rows null: {bool(np.isnan(got[-h:]).all())}; label_end ok: {le_ok}")
    record("Targets are forward returns from the decision price", t_ok, "; ".join(t_detail) +
           ". P[t] is the last trade price at or before the close of bar t; empty minutes carry the last "
           "price forward (forward fill only ever looks backwards).")

    # 6. features vs targets
    dev = rd.filter(pl.col("ts") < pl.lit(rs["holdout"]["start"]).str.to_datetime(time_zone="UTC"))
    samp = dev.gather_every(7)
    mx = []
    for f in FEATS:
        for h in rs["horizons"]:
            c = samp.select(pl.corr(f, f"fwd_ret_{h}")).item()
            mx.append((abs(c) if c is not None and np.isfinite(c) else 0.0, f, h))
    mx.sort(reverse=True)
    # exact equality is only informative where the target is non-zero (0 == 0 happens for a flat minute and a
    # zero imbalance, or hour_sin at midnight); flag a feature if >0.01% of non-zero-target rows match exactly
    eq, eq_max = [], 0.0
    for f in FEATS:
        for h in rs["horizons"]:
            share = samp.filter(pl.col(f"fwd_ret_{h}") != 0).select((pl.col(f) == pl.col(f"fwd_ret_{h}")).mean()).item() or 0.0
            eq_max = max(eq_max, share)
            if share > 1e-4:
                eq.append((f, h, share))
    record("No feature mirrors a target", mx[0][0] < 0.3 and not eq,
           f"Largest |Pearson corr(feature, fwd_ret_h)| on development data (every 7th minute): "
           f"{mx[0][0]:.4f} ({mx[0][1]}, h={mx[0][2]}); next: {mx[1][0]:.4f} ({mx[1][1]}, h={mx[1][2]}). "
           f"Exact equality with a non-zero target: max share over all feature/horizon pairs {eq_max:.2e} "
           f"(threshold 1e-4); flagged pairs: {eq or 'none'}.")

    # 7. folds
    wf = rs["walk_forward"]
    folds = V.walk_forward_folds(wf["start"], wf["first_validation"], wf["end_exclusive"], wf["block_months"],
                                 timedelta(days=wf["embargo_days"]))
    f_ok, f_rows = True, []
    for h in rs["horizons"]:
        for fo in folds:
            tr, va = V.split(dev, fo, h, stride=1)
            c1 = tr[f"label_end_{h}"].max() <= fo.valid_start - timedelta(days=wf["embargo_days"])
            c2 = va[f"label_end_{h}"].max() <= fo.valid_end
            c3 = tr["ts"].max() < va["ts"].min()
            f_ok &= bool(c1 and c2 and c3)
        f_rows.append(f"h={h}: all {len(folds)} folds pass (train label end <= valid start - embargo; "
                      f"valid labels end inside block; train strictly before validation)")
    hs = V._d(rs["holdout"]["start"])
    last_dev_label = dev.filter(pl.col(f"fwd_ret_{rs['primary_horizon']}").is_not_null())
    f_ok &= bool(dev["ts"].max() < hs)
    record("Walk-forward purge / embargo / holdout separation", f_ok,
           "; ".join(f_rows) + f". Development rows end at {dev['ts'].max()}; the development rows whose label "
           "reaches into the holdout are dropped from every development fit because validation requires "
           "label_end <= block end (the last block ends at the holdout start).")

    # 8. preprocessing inside pipelines
    src = inspect.getsource(M)
    record("Learned preprocessing fitted inside each training fold",
           "make_pipeline(SimpleImputer" in src and "StandardScaler" in src,
           "Logistic regression = Pipeline(SimpleImputer(median, add_indicator) -> StandardScaler -> "
           "LogisticRegression); Random forest = Pipeline(SimpleImputer -> RF); LightGBM handles missing values "
           "natively. Pipelines are re-fitted from scratch on each training fold, so no scaling or imputation "
           "parameter ever sees validation or holdout rows. Feature z-scores use trailing windows only (check 1).")

    lines.insert(2, f"**Overall: {'PASS - no leakage detected' if ok_all else 'FAIL - see below'}**\n")
    lines.append("## Design rules enforced in code\n\n"
                 "- Decision time for bar t is its close (ts + 1 min); the trade executes at the VWAP of bar t+1 "
                 "(`backtest.py`), never at the price that produced the signal.\n"
                 "- All rolling windows are trailing (`rolling_*` in Polars end at the current row); no `shift(-k)` "
                 "appears in `features.py` (negative shifts exist only in `targets.py`).\n"
                 "- No backward fill anywhere; forward fill only for the last traded price.\n"
                 "- Regime cut-offs and the large-trade size threshold are estimated on the initial training window "
                 "(2023-03-01 .. 2024-02-29) only.\n"
                 "- Holdout rows are only reachable through `validation.unlock_holdout`, which refuses without "
                 "`docs/final_methodology.md` and logs every access with that file's SHA-256 "
                 "(`reports/holdout_access_log.jsonl`).\n")
    src_f = (ROOT / "src" / "ethof" / "features.py").read_text()
    neg = [l.strip() for l in src_f.splitlines() if "shift(-" in l or "backward_fill" in l]
    lines.append(f"Static scan of features.py for negative shifts / backward fills: {neg or 'none found'}.\n")
    out = ROOT / "docs" / "leakage_audit.md"
    out.write_text("\n".join(lines))
    print("\n".join(lines))
    sys.exit(0 if ok_all else 1)


if __name__ == "__main__":
    main()
