#!/usr/bin/env python3
"""Generate and execute the narrative notebooks in notebooks/.

The notebooks are thin: the heavy computation lives in scripts/ and src/ethof (reproducible from the
command line); each notebook loads the tables and figures those scripts wrote and displays them with a short
explanation, so every number shown is read from a pipeline output, never typed in.

    python scripts/make_notebooks.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import nbformat as nbf
from nbconvert.preprocessors import ExecutePreprocessor

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks"

SETUP = """import json, polars as pl
from pathlib import Path
from IPython.display import Image, Markdown, display
ROOT = Path.cwd().parent
T = ROOT / "reports" / "tables"; F = ROOT / "reports" / "figures"
pl.Config.set_tbl_rows(40); pl.Config.set_tbl_cols(20); pl.Config.set_tbl_width_chars(200)
def show(p): display(Image(filename=str(p)))
def tab(p, cols=None):
    d = pl.read_csv(p); return d.select(cols) if cols else d"""

BOOKS = {
    "01_data_quality": [
        ("md", "# 01 · Data quality\nSource: Binance USDⓈ-M futures public archive, ETHUSDT perpetual, 2023-03-01 → 2026-09-30. "
               "The full report is generated by `scripts/run_stage2.py` (`docs/data_quality_report.md`). This notebook "
               "shows the key tables. Every value is read from the pipeline outputs."),
        ("code", "display(Markdown((ROOT / 'docs' / 'data_quality_report.md').read_text().split('## 3.')[0]))"),
        ("md", "## Extreme one-minute moves (kept: liquidation cascades, not errors)"),
        ("code", "tab(ROOT / 'docs/stage2/extreme_1m_bars.csv', ['ts','open','high','low','close','n_trades','logret','classification']).head(15)"),
        ("md", "## Order-book coverage gaps (flagged, never interpolated)"),
        ("code", "tab(ROOT / 'docs/stage2/book_short_days.csv')"),
        ("md", "## Empirical check of the bookDepth sign convention and time zone"),
        ("code", "tab(ROOT / 'docs/stage2/book_sign_timezone_check.csv')"),
        ("md", "## Quoted spread (bookTicker sample days) used in the cost model"),
        ("code", "tab(T / 'spread_measurement.csv')"),
    ],
    "02_eda": [
        ("md", "# 02 · Exploratory analysis (development period only)\nEach chart answers one question; the holdout "
               "(2025-10 → 2026-09) is excluded."),
        ("code", "show(F / 'eda/01_price_vol_volume_funding.png')"),
        ("md", "**Are returns Gaussian?** Heavy tails matter for the choice of tests (HAC, bootstrap) and for risk."),
        ("code", "show(F / 'eda/02_return_tails.png'); tab(T / 'eda_return_distribution.csv')"),
        ("md", "**Is there linear return autocorrelation? Volatility clustering?**"),
        ("code", "show(F / 'eda/03_autocorrelation.png')"),
        ("md", "**Intraday seasonality** motivates the hour-of-day features and the trailing 1-day z-scores."),
        ("code", "show(F / 'eda/04_intraday_seasonality.png')"),
        ("md", "**How are order-flow and book imbalances distributed?**"),
        ("code", "show(F / 'eda/05_imbalance_distributions.png'); tab(T / 'eda_imbalance_summary.csv')"),
        ("code", "show(F / 'eda/06_feature_correlation.png')"),
        ("code", "json.loads((T / 'stats_summary.json').read_text())"),
    ],
    "03_statistical_alpha": [
        ("md", "# 03 · Statistical alpha tests (development period)\nHAC (Newey-West, 2h lags) regressions of h-minute "
               "forward returns on standardised signals, a non-overlapping re-check, controls, decile spreads with a "
               "5-day moving-block bootstrap, and Holm/BH adjustment over the whole family of tests."),
        ("code", "tab(T / 'stats_univariate_predictive.csv', ['signal','h','pearson','beta_bps_per_sd','t_hac','p_hac','p_holm','p_bh','t_nonoverlap'])"),
        ("md", "## Does the signal survive momentum, volatility and volume controls?"),
        ("code", "tab(T / 'stats_with_controls.csv')"),
        ("md", "## Decile analysis"),
        ("code", "show(F / 'stats/decile_forward_returns.png'); tab(T / 'stats_decile_spreads.csv')"),
        ("md", "## Event study: extreme order flow"),
        ("code", "show(F / 'stats/event_study.png'); tab(T / 'stats_event_study.csv')"),
        ("md", "## Stability across quarters"),
        ("code", "show(F / 'stats/quarterly_ic.png'); tab(T / 'stats_quarterly_rank_ic.csv')"),
    ],
    "04_feature_ablation": [
        ("md", "# 04 · Feature ablation\nA = price, B = +volume, C = +trade flow, D = +order-book bands, E = +funding/OI. "
               "Development walk-forward (7 folds) and the frozen holdout evaluation."),
        ("code", "s = tab(T / 'model_summary.csv'); s.filter(pl.col('h') == 15).select('config','auc_mean','auc_sd','auc_min','folds_auc_gt_05','ll_improvement_mean','ic_mean')"),
        ("code", "tab(T / 'dev_ablation_economics.csv')"),
        ("md", "## Holdout (frozen methodology)"),
        ("code", "p = T / 'holdout' / 'ablation.csv'\ntab(p) if p.exists() else 'not yet evaluated'"),
    ],
    "05_modeling": [
        ("md", "# 05 · Models\nLogistic regression (L2), random forest, LightGBM, plus rule baselines scored as classifiers."),
        ("code", "tab(T / 'lgbm_tuning.csv')"),
        ("code", "json.loads((T / 'lgbm_selected_params.json').read_text())"),
        ("code", "tab(T / 'baseline_rules_folds.csv').group_by('rule','h').agg(pl.col('auc').mean()).sort('h','rule')"),
        ("md", "## Alternative targets (3-class with neutral band, regression)"),
        ("code", "tab(T / 'model_folds_all.csv').filter(pl.col('task') != 'binary').select('config','fold','auc_ovr_macro','auc_up_vs_down_excl_neutral','share_neutral','mae_bps','mae_zero_bps','rmse_bps','rmse_mean_bps','ic_spearman','hit_rate_sign')"),
        ("md", "## Interpretability (out of sample, fold F6)"),
        ("code", "show(F / 'interpret/permutation_importance.png'); tab(T / 'interpret_group_permutation.csv')"),
        ("code", "show(F / 'interpret/shap_dependence.png'); tab(T / 'interpret_feature_importance.csv').head(15)"),
    ],
    "06_walk_forward": [
        ("md", "# 06 · Walk-forward validation\nExpanding window, 3-month validation blocks, purge (labels may not cross into "
               "the embargo) and a 1-day embargo. Random cross-validation is not used: neighbouring minutes share "
               "overlapping labels and regimes, so shuffling would leak future information into training."),
        ("code", "tab(T / 'walk_forward_folds.csv')"),
        ("code", "tab(T / 'model_folds_all.csv').filter(pl.col('config') == json.loads((T / 'primary_model_selection.json').read_text())['selected']).select('fold','valid_start','n_train','n','auc','log_loss','log_loss_baseline','ece','ic_spearman')"),
        ("code", "show(F / 'dev/dev_monthly_stability.png')"),
    ],
    "07_backtest": [
        ("md", "# 07 · Signals and cost-aware backtest (development out-of-fold)\nSignal at bar close, execution at the next "
               "bar's VWAP, staggered 15-minute holding, fees + slippage + half spread, funding charged at settlement."),
        ("code", "json.loads((T / 'primary_model_selection.json').read_text())"),
        ("code", "tab(T / 'dev_delta_selection.csv')"),
        ("code", "tab(T / 'dev_backtest_summary.csv', ['strategy','cost','total_return','sharpe','max_drawdown','n_trades','win_rate','avg_trade_bps','breakeven_cost_bps_per_side','turnover_per_day'])"),
        ("code", "show(F / 'dev/dev_equity_drawdown.png')"),
        ("code", "tab(T / 'dev_regimes.csv')"),
    ],
    "08_final_results": [
        ("md", "# 08 · Final untouched holdout (2025-10-01 → 2026-09-30)\nEvaluated once, with the methodology frozen in "
               "`docs/final_methodology.md`; the access log records the SHA-256 of that file."),
        ("code", "print((ROOT / 'reports' / 'holdout_access_log.jsonl').read_text())"),
        ("code", "H = T / 'holdout'; json.loads((H / 'summary.json').read_text())['primary_classification_pooled']"),
        ("code", "tab(H / 'primary_blocks.csv', ['block','valid_start','n_train','n','auc','log_loss','log_loss_baseline','ic_spearman'])"),
        ("code", "tab(H / 'backtest_summary.csv', ['strategy','cost','total_return','ann_return','sharpe','sortino','max_drawdown','calmar','n_trades','win_rate','profit_factor','avg_trade_bps','breakeven_cost_bps_per_side','turnover_per_day','exposure','sum_funding'])"),
        ("code", "show(F / 'holdout/equity_drawdown_exposure.png'); show(F / 'holdout/rolling_sharpe_distribution_costs.png')"),
        ("code", "tab(H / 'cost_sensitivity_ml.csv')"),
        ("code", "tab(H / 'regimes.csv'); "),
        ("code", "tab(H / 'monthly_stability.csv')"),
        ("code", "tab(H / 'confirmatory_tests.csv')"),
        ("code", "tab(H / 'horizons.csv')"),
        ("md", "## Replication on SOLUSDT (same frozen methodology)"),
        ("code", "R = T / 'replication_SOLUSDT'\ntab(R / 'backtest_summary.csv', ['strategy','cost','total_return','sharpe','max_drawdown','n_trades','breakeven_cost_bps_per_side']) if (R / 'backtest_summary.csv').exists() else 'not evaluated'"),
    ],
}


def main() -> None:
    NB.mkdir(exist_ok=True)
    ep = ExecutePreprocessor(timeout=600, kernel_name="python3")
    for name, cells in BOOKS.items():
        nb = nbf.v4.new_notebook()
        nb.cells = [nbf.v4.new_code_cell(SETUP)] + [
            nbf.v4.new_markdown_cell(c) if k == "md" else nbf.v4.new_code_cell(c) for k, c in cells]
        ep.preprocess(nb, {"metadata": {"path": str(NB)}})
        nbf.write(nb, NB / f"{name}.ipynb")
        print("executed", name, flush=True)


if __name__ == "__main__":
    sys.exit(main())
