"""Method validation on SYNTHETIC data: negative and positive controls.

Writes reports/pipeline_validation.md and reports/tables/pipeline_controls.csv.
These numbers describe the RESEARCH METHOD (false-positive rate, power),
NOT Bitcoin.

    python scripts/pipeline_controls.py --neg 40 --pos 20
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "tests"))

from src import config  # noqa: E402
from test_pipeline_controls import _run  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--neg", type=int, default=40)
    ap.add_argument("--pos", type=int, default=20)
    a = ap.parse_args()
    rows = []
    for beta, n in [(0.0, a.neg), (0.3, a.pos)]:
        for s in range(n):
            auc, lo, hi, p = _run(beta=beta, seed=1000 + s)
            rows.append(dict(control="negative (random walk)" if beta == 0 else "positive (beta=0.3 momentum)",
                             seed=1000 + s, auc=auc, auc_ci_low=lo, auc_ci_high=hi,
                             ci_excludes_half=(lo > 0.5) or (hi < 0.5),
                             gross_sharpe=p["gross_sharpe"], net_sharpe=p["sharpe"]))
            print(rows[-1], flush=True)
    df = pd.DataFrame(rows)
    config.TABLES_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(config.TABLES_DIR / "pipeline_controls.csv", index=False)
    s = df.groupby("control").agg(runs=("auc", "size"), mean_auc=("auc", "mean"),
                                  share_ci_excludes_half=("ci_excludes_half", "mean"),
                                  mean_gross_sharpe=("gross_sharpe", "mean"),
                                  sd_gross_sharpe=("gross_sharpe", "std"),
                                  mean_net_sharpe=("net_sharpe", "mean"),
                                  share_net_positive=("net_sharpe", lambda x: (x > 0).mean()))
    neg = s.loc["negative (random walk)"]
    pos = s.loc["positive (beta=0.3 momentum)"]
    md = f"""# Pipeline validation (synthetic controls; about the METHOD, not about Bitcoin)

Generated by `scripts/pipeline_controls.py`. Each run creates a 240-day synthetic 1-minute price path and pushes it through the **same code** used for the real data: features, walk-forward logistic regression (C = 0.1), a long/short signal, and a backtest at base costs of 7 bp per side. The evaluation covers about 6 months of hourly decisions.

| Control | Runs | Mean AUC | Share of runs where the AUC 95% CI excludes 0.5 | Mean gross Sharpe (sd) | Mean net Sharpe | Share with net Sharpe > 0 |
|---|---|---|---|---|---|---|
{chr(10).join(f"| {i} | {int(r.runs)} | {r.mean_auc:.4f} | {r.share_ci_excludes_half:.1%} | {r.mean_gross_sharpe:+.2f} ({r.sd_gross_sharpe:.2f}) | {r.mean_net_sharpe:+.2f} | {r.share_net_positive:.1%} |" for i, r in s.iterrows())}

## What this shows

* **Negative control (no signal exists):** the mean AUC is {neg.mean_auc:.4f} and the mean gross Sharpe is {neg.mean_gross_sharpe:+.2f}, so the pipeline has **no systematic bias towards finding an edge**, which a look-ahead bug would create. The share of null runs whose AUC confidence interval wrongly excludes 0.5 is **{neg.share_ci_excludes_half:.1%}** against a nominal 5%. {"That is close to nominal." if neg.share_ci_excludes_half <= 0.08 else "That is ABOVE nominal: the block-bootstrap AUC interval is too narrow on this design, so we do not rely on it alone. The permutation test and the HAC log-loss test are required as well."}
* **Single-run noise:** across random walks the gross Sharpe has a standard deviation of {neg.sd_gross_sharpe:.2f} over about half a year. One backtest showing a Sharpe of 1–2 is therefore **entirely consistent with zero skill**. This is the strongest argument for out-of-sample discipline and the Deflated Sharpe Ratio.
* **Costs:** with no edge, trading every hour loses money in {1 - neg.share_net_positive:.0%} of runs at 14 bp round trip. Turnover alone destroys a strategy that has no edge.
* **Positive control (a real signal exists, beta = 0.3):** mean AUC {pos.mean_auc:.4f}; the interval excludes 0.5 in {pos.share_ci_excludes_half:.0%} of runs. The pipeline **detects a genuine signal of this size**. (Beta = 0.3 is a strong effect, chosen to test detection rather than to resemble BTC.)
"""
    (config.REPORTS_DIR / "pipeline_validation.md").write_text(md)
    print(s)


if __name__ == "__main__":
    main()
